spring:
  main:
    web-application-type: servlet

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tiary;MODE=MYSQL
    username: sa

  sql:
    init:
      schema-locations: classpath*:database/schema.sql

  jpa:
    show-sql: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true